import rawLekkungDiff from '@/data/scans/lekkung_diff.json';
import rawSepaDiff from '@/data/scans/sepa_diff.json';
import rawKellDiff from '@/data/scans/oliver_kell_diff.json';
import rawOneilDiff from '@/data/scans/oneil_diff.json';
import rawBreakoutDiff from '@/data/scans/breakout_diff.json';
import rawMarketStageDiff from '@/data/scans/market_stage_diff.json';
import rawStageAnalysisDiff from '@/data/scans/weinstein_diff.json';

// Batch-generated by scripts/compute_scan_diff.py - same static-import
// convention as lib/scanHistory.ts / lib/scanDays.ts.

export interface ScanDiffDropped {
  ticker: string;
  lastClose: number | null;
}

export interface ScanDiffData {
  generatedAt: string;
  scan: string;
  previousDate: string;
  currentDate: string;
  newTickers: string[];
  droppedTickers: ScanDiffDropped[];
}

const DIFF_BY_SCAN: Record<string, ScanDiffData> = {
  lekkung: rawLekkungDiff as unknown as ScanDiffData,
  sepa: rawSepaDiff as unknown as ScanDiffData,
  kell: rawKellDiff as unknown as ScanDiffData,
  oneil: rawOneilDiff as unknown as ScanDiffData,
  breakout: rawBreakoutDiff as unknown as ScanDiffData,
  'market-stage': rawMarketStageDiff as unknown as ScanDiffData,
  'stage-analysis': rawStageAnalysisDiff as unknown as ScanDiffData,
};

export function getScanDiff(scanName: string): ScanDiffData | null {
  return DIFF_BY_SCAN[scanName] ?? null;
}
