import rawLekkungHistory from '@/data/scans/lekkung_history.json';

// Batch-generated by scripts/compute_scan_history.py, same static-import
// convention as lib/scanDays.ts / lib/strategyData.ts (data/scans/*.json is
// baked in at build time, not fetched at runtime).

export interface ScanHistoryTicker {
  ticker: string;
  hitDates: string[]; // ISO dates, ascending, within the batch's window (90d)
  hitCount: number;
  closeByDate: Record<string, number>;
  firstSeen: string;
  lastSeen: string;
  firstClose: number;
  lastClose: number;
  pctChange: number | null;
}

export interface ScanHistoryData {
  generatedAt: string;
  scan: string;
  windowDays: number;
  tickers: ScanHistoryTicker[];
}

// scan name -> statically-imported history data. Add one import + one entry
// here to extend the /history view to another scan - ScanHistoryView.tsx
// itself takes scanName as a prop and needs no other changes.
const HISTORY_BY_SCAN: Record<string, ScanHistoryData> = {
  lekkung: rawLekkungHistory as ScanHistoryData,
};

export function getScanHistory(scanName: string): ScanHistoryData | null {
  return HISTORY_BY_SCAN[scanName] ?? null;
}
