export const stockNames: Record<string, string> = {
  // Banking
  KBANK: 'Kasikorn Bank',
  BBL: 'Bangkok Bank',
  SCB: 'SCB X',
  KTB: 'Krungthai Bank',
  BAY: 'Bank of Ayudhya (Krungsri)',
  TTB: 'TMBThanachart Bank',
  TISCO: 'Tisco Financial Group',
  KKP: 'Kiatnakin Phatra',
  TCAP: 'Thanachart Capital',
  BKIH: 'Bangkok Insurance',
  // Finance & Credit
  KTC: 'Krungthai Card',
  JMT: 'JMT Network Services',
  BAM: 'Bangkok Commercial Asset',
  MTC: 'Muangthai Capital',
  SAWAD: 'Sawad Technology',
  TIDLOR: 'Ngern Tidlor',
  AEONTS: 'AEON Thailand',
  THANI: 'Ratchthani Leasing',
  NCAP: 'Nakornchaisri Automobile',
  ASK: 'AECS Security',
  CREDIT: 'Credit Corp',
  SCAP: 'S-Capital',
  LHFG: 'LH Financial Group',
  KTBSTMR: 'KTB Securities',
  KGI: 'KGI Securities',
  // Insurance
  TLI: 'Thai Life Insurance',
  BLA: 'Bangkok Life Assurance',
  AYUD: 'Ayudhya Insurance',
  // Energy
  GULF: 'Gulf Energy Development',
  GUNKUL: 'Gunkul Engineering',
  RATCH: 'Ratchaburi Electricity',
  EGCO: 'Electricity Generating',
  GPSC: 'Global Power Synergy',
  BGRIM: 'B.Grimm Power',
  BCPG: 'BCPG PCL',
  EA: 'Energy Absolute',
  CKP: 'CK Power',
  GENCO: 'General Engineering',
  PTT: 'PTT PCL',
  PTTEP: 'PTT Exploration & Production',
  OR: 'PTT Oil and Retail',
  PTG: 'PTG Energy',
  PTTGC: 'PTT Global Chemical',
  TOP: 'Thai Oil',
  IRPC: 'IRPC PCL',
  SPRC: 'Star Petroleum Refining',
  BCP: 'Bangchak',
  TASCO: 'Tipco Asphalt',
  EASTW: 'Eastern Water Resources',
  TTW: 'TTW PCL',
  WHAUP: 'WHA Utilities and Power',
  BANPU: 'Banpu PCL',
  // Technology
  DELTA: 'Delta Electronics (Thailand)',
  HANA: 'Hana Microelectronics',
  KCE: 'KCE Electronics',
  SVI: 'SVI PCL',
  SMT: 'Siam Melamine Thailand',
  CCET: 'Cal Comp Electronics',
  MGC: 'MGC Asia',
  STANLY: 'Stanley Electric (Thailand)',
  SAT: 'Somboon Advance Technology',
  HTECH: 'H Technology',
  YUASA: 'GS Yuasa (Thailand)',
  ALUCON: 'Alucon',
  FORTH: 'Forth Corporation',
  TEAM: 'Team Precision',
  DITTO: 'Ditto Thailand',
  IT: 'Intouch Technology',
  INSET: 'Inset PCL',
  SVOA: 'SVOA PCL',
  SAMART: 'Samart Corporation',
  SYNEX: 'Synnex Thailand',
  VCOM: 'VCOM PCL',
  SECURE: 'Secure A PCL',
  NETBAY: 'NetBay PCL',
  TEAMG: 'Team Group',
  ADVANC: 'Advanced Info Service (AIS)',
  TRUE: 'True Corporation',
  THCOM: 'Thaicom',
  JAS: 'Jasmine International',
  DMT: 'Digital Media & Technology',
  // Materials
  IVL: 'Indorama Ventures',
  GC: 'PTT Global Chemical (GC)',
  TOA: 'TOA Paint',
  TPIPL: 'TPI Polene Power',
  UKEM: 'UKEM PCL',
  TPLAS: 'Thai Plaspac',
  SCC: 'Siam Cement Group',
  SCGP: 'SCG Packaging',
  SCCC: 'Siam City Cement',
  BGC: 'Bangkok Glass',
  EPG: 'Eastern Polymer Group',
  SCGD: 'SCG Decor',
  TRUBB: 'Thai Rubber Latex',
  NER: 'Northeast Rubber',
  STA: 'Sri Trang Agro-Industry',
  // Industrials
  STECON: 'Steel Technologies',
  CK: 'Ch. Karnchang',
  SEAFCO: 'Seafco PCL',
  PYLON: 'Pylon PCL',
  CMAN: 'Chuang Aik',
  NDR: 'NDR PCL',
  CTW: 'CTW PCL',
  AMATA: 'Amata Corporation',
  WHA: 'WHA Corporation',
  ROJNA: 'Rojana Industrial Park',
  WHART: 'WHA Premium REIT',
  TAE: 'TAE PCL',
  EURO: 'Euro Shoes & Accessories',
  TSTH: 'Thai Steel Products',
  TRT: 'Thai Rubber & Allied',
  AXTRART: 'Axtar PCL',
  STPI: 'Steel Technologies & Products',
  // Consumer Products
  TU: 'Thai Union Group',
  CPF: 'Charoen Pokphand Foods',
  GFPT: 'GFPT PCL',
  TFG: 'Thai Foods Group',
  TVO: 'Thai Vegetable Oil',
  CBG: 'Carabao Group',
  XO: 'XO Food PCL',
  ICHI: 'Ichitan Group',
  M: 'MK Restaurant Group',
  MAGURO: 'Maguro PCL',
  BJC: 'Berli Jucker',
  OSP: 'Osotspa PCL',
  MOSHI: 'Moshi Moshi',
  AURA: 'Aura PCL',
  KSL: 'Kaset Thai International Sugar',
  // Property
  SIRI: 'Sansiri',
  SPALI: 'Supalai PCL',
  AP: 'AP Thailand',
  LH: 'Land and Houses',
  QH: 'Quality Houses',
  AMATAR: 'Amata VN PCL',
  AIMIRT: 'AIM Industrial REIT',
  SPRIME: 'S Prime REIT',
  'B-WORK': 'B Office Work REIT',
  LHHOTEL: 'LH Hotel REIT',
  AWC: 'Asset World Corporation',
  CPN: 'Central Pattana',
  IMPACT: 'Impact Exhibition',
  MBK: 'MBK PCL',
  // Services
  AOT: 'Airports of Thailand',
  BA: 'Bangkok Airways',
  AAV: 'Asia Aviation',
  THAI: 'Thai Airways',
  RCL: 'Regional Container Lines',
  PSL: 'Precious Shipping',
  BEM: 'Bangkok Expressway & Metro',
  BTS: 'BTS Group Holdings',
  PRM: 'Prinsiri PCL',
  ERW: 'The Erawan Group',
  CENTEL: 'Centara Hotels & Resorts',
  MINT: 'Minor International',
  SHR: 'S Hotels and Resorts',
  BH: 'Bumrungrad Hospital',
  BDMS: 'Bangkok Dusit Medical',
  CHG: 'Chularat Hospital Group',
  BCH: 'Bangkok Chain Hospital',
  LHSC: 'LH Shopping Center',
  MEGA: 'Mega Lifesciences',
  PLANB: 'Plan B Media',
  MONO: 'Mono Next',
  MAJOR: 'Major Cineplex',
  ONEE: 'One Entertainment',
  NATION: 'Nation Multimedia',
  VGI: 'VGI PCL',
  CPALL: 'CP All',
  CRC: 'Central Retail Corporation',
  HMPRO: 'HomePro PCL',
  DOHOME: 'Do Home PCL',
  JMART: 'JMart PCL',
  MC: 'MC Fashion',
  GLOBAL: 'Global House',
  SINGER: 'Singer Thailand',
  COM7: 'Com Seven',
  ADVICE: 'Advice IT Infinite',
  CPAXT: 'CPA eXtra',
};
