"""
validate_sector_mapping.py — catch sector_map.json drift before it ships.

sector_map.json (data/scans/sector_map.json) is a hand-curated snapshot, not
generated by the data_engine pipeline — nothing regenerates it when the SET
universe changes, so tickers added/reclassified after the last manual update
silently show up as sector "N/A" on the dashboard. This script diffs the
freshly-copied scan output's ticker list against sector_map.json's coverage
and prints a loud warning (non-fatal — this must not block the pipeline)
so a human notices in the console instead of discovering it later via the
web app's own runtime console.warn (app/page.tsx).

Run at the end of update_stockdesk.bat, after Step 5 (copy) so it checks the
data that's about to be committed.
"""
import json
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

SCANS_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'scans')
SECTOR_MAP_FILE = os.path.join(SCANS_DIR, 'sector_map.json')
STAGE_FILE = os.path.join(SCANS_DIR, 'market_stage.json')


def main():
    if not os.path.exists(SECTOR_MAP_FILE) or not os.path.exists(STAGE_FILE):
        print(f"[sector-validate] SKIP - missing {SECTOR_MAP_FILE} or {STAGE_FILE}")
        return 0

    with open(SECTOR_MAP_FILE, 'r', encoding='utf-8') as f:
        sector_map = json.load(f)
    mapped = set(sector_map.get('ticker_to_sector', {}).keys())

    with open(STAGE_FILE, 'r', encoding='utf-8') as f:
        stage = json.load(f)
    universe = {row['Ticker'] for row in stage if row.get('Ticker')}

    missing = sorted(universe - mapped)

    if missing:
        print(f"[sector-validate] WARNING: {len(missing)} ticker(s) in the current "
              f"{len(universe)}-ticker universe have no sector_map.json mapping "
              f"(will show as sector \"N/A\" on the dashboard):")
        print(f"  {', '.join(missing)}")
        print(f"  -> patch data/scans/sector_map.json's \"ticker_to_sector\" "
              f"(and the matching \"sectors[].tickers\" bucket) for these before deploying.")
    else:
        print(f"[sector-validate] OK - all {len(universe)} universe tickers have a sector mapping.")

    return 0  # never fail the pipeline over this — it's a warning, not a hard error


if __name__ == '__main__':
    sys.exit(main())
